# Generated by Django 2.1.7 on 2019-04-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CNIC',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
