# Generated by Django 2.1.7 on 2019-04-09 10:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190409_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
