# Generated by Django 2.1.7 on 2019-04-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190409_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CNIC',
            field=models.CharField(max_length=13),
        ),
    ]
