# Generated by Django 2.1.7 on 2019-04-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190409_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Status',
            field=models.CharField(default='Pending', max_length=50),
            preserve_default=False,
        ),
    ]
