# Generated by Django 2.1.7 on 2019-04-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190410_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorsubjects',
            name='Board',
        ),
        migrations.AddField(
            model_name='subject',
            name='Board',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='main.Board'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='MyUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.MyUser'),
        ),
    ]
