# Generated by Django 2.1.7 on 2019-04-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190410_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Board',
            new_name='board',
        ),
    ]
