# Generated by Django 2.1.7 on 2019-04-17 04:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190417_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
