# Generated by Django 2.1.7 on 2019-04-21 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190417_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('receivingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_received_messages', to='main.MyUser')),
                ('sendingUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sent_messages', to='main.MyUser')),
            ],
        ),
    ]
