# Generated by Django 2.1.7 on 2019-04-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190421_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='message',
        ),
    ]
