# Generated by Django 2.1.7 on 2019-04-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190422_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('userRating', models.IntegerField()),
                ('tutorRating', models.IntegerField()),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CUser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tutor')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='CNIC',
            field=models.IntegerField(),
        ),
    ]
