# Generated by Django 2.1.7 on 2019-04-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190422_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractsTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStart', models.TimeField()),
                ('timeEnd', models.TimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Contracts')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Day')),
            ],
        ),
    ]
