# Generated by Django 2.1.7 on 2019-04-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contractstimes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='cuser',
        ),
        migrations.AddField(
            model_name='contracts',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Student'),
            preserve_default=False,
        ),
    ]
