# Generated by Django 2.1.7 on 2019-04-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190425_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='tutorRating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='userRating',
            field=models.IntegerField(null=True),
        ),
    ]
