# Generated by Django 2.1.7 on 2019-04-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190425_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='tutorRating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='userRating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
