# Generated by Django 2.1.7 on 2019-05-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190504_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(default='Pending_View', max_length=100),
            preserve_default=False,
        ),
    ]
