# Generated by Django 2.1.7 on 2019-05-04 14:17

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_messages_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='Position',
            field=geoposition.fields.GeopositionField(default='8.7832, 124.5085', max_length=42),
        ),
    ]
