# Generated by Django 2.1.7 on 2019-05-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tutor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='hash',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
