# Generated by Django 2.1.7 on 2019-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_tutor_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='hash',
            field=models.CharField(max_length=100),
        ),
    ]
