# Generated by Django 2.1.7 on 2019-05-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190513_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='conversation',
            field=models.CharField(default='0_0', max_length=100),
            preserve_default=False,
        ),
    ]
